app:
  name: "YAML Config Application"
  environment: "default"
  port: 3000

database:
  host: "localhost"
  port: 5432
  user: "default_user"
  password: "bootcamp"
  dbName: "default_db"

logger:
  level: "info"

api:
  key: "default-api-key"
  url: "https://default.example.com"
